apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-helloworld
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-helloworld
    spec:
      containers:
        - name: helloworld-app
          image: {{.Values.helloworld.image.name}}:{{.Chart.AppVersion}}
          ports:
            - containerPort: 3000
